export enum Message {
  GET_PREFERENCES = 'get_preferences',
  SET_PREFERENCES = 'set_preferences',
  GET_GENERAL_NEWS = 'get_general_news',
  GET_NEWS = 'get_news',
  GET_SPORTS_NEWS = 'get_sports_news',
  HEALTH_CHECK = 'health_check',
  VALIDATE_USER = 'validate_user',
  CREATE_USER = 'create_user',
  GET_TICKERS = 'get_tickers',
  GET_CURRENCY = 'get_currency',
  GET_FINANCE = 'get_finance',
  GET_ENTERTAINMENT = 'get_entertainment',
  GET_TECH = 'get_tech',
}
