global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['172.17.0.1:3000']
  - job_name: 'user-service'
    static_configs:
      - targets: ['172.17.0.1:4001']
  - job_name: 'news-service'
    static_configs:
      - targets: ['172.17.0.1:4002']
    metrics_path: '/metrics'
  - job_name: 'sports-service'
    static_configs:
      - targets: ['172.17.0.1:4003']
    metrics_path: '/metrics'